# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(469, 367)
        Dialog.setStyleSheet("QLabel{\n"
"font: 10pt \"Bahnschrift SemiCondensed\";\n"
"\n"
"}\n"
"\n"
"#btnEdit {\n"
"    background-color: #48ACAC;\n"
"    border-radius:50px;\n"
"    color:white;\n"
"font: 14pt \"Bahnschrift SemiCondensed\";\n"
"\n"
"}\n"
"#btnEdit:hover{\n"
"background-color: #2F958D;\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #fff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid gray;\n"
"    padding: 5px;\n"
"    padding-left: 5px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid gray;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: black;    \n"
"    background-color: white;\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.cmbxAcceptedOrRejected = QtWidgets.QComboBox(self.frame)
        self.cmbxAcceptedOrRejected.setMinimumSize(QtCore.QSize(0, 35))
        self.cmbxAcceptedOrRejected.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbxAcceptedOrRejected.setStyleSheet("")
        self.cmbxAcceptedOrRejected.setObjectName("cmbxAcceptedOrRejected")
        self.cmbxAcceptedOrRejected.addItem("")
        self.cmbxAcceptedOrRejected.addItem("")
        self.gridLayout.addWidget(self.cmbxAcceptedOrRejected, 1, 1, 1, 1)
        self.cmbxWalkthroughOrButton = QtWidgets.QComboBox(self.frame)
        self.cmbxWalkthroughOrButton.setMinimumSize(QtCore.QSize(0, 35))
        self.cmbxWalkthroughOrButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbxWalkthroughOrButton.setStyleSheet("")
        self.cmbxWalkthroughOrButton.setObjectName("cmbxWalkthroughOrButton")
        self.cmbxWalkthroughOrButton.addItem("")
        self.cmbxWalkthroughOrButton.addItem("")
        self.gridLayout.addWidget(self.cmbxWalkthroughOrButton, 0, 1, 1, 1)
        self.projectid_label_2 = QtWidgets.QLabel(self.frame)
        self.projectid_label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.projectid_label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.projectid_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.projectid_label_2.setObjectName("projectid_label_2")
        self.gridLayout.addWidget(self.projectid_label_2, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 0, 1, 1)
        self.projectid_label = QtWidgets.QLabel(self.frame)
        self.projectid_label.setMinimumSize(QtCore.QSize(70, 0))
        self.projectid_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.projectid_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.projectid_label.setObjectName("projectid_label")
        self.gridLayout.addWidget(self.projectid_label, 0, 0, 1, 1)
        self.dateInspection = QtWidgets.QDateEdit(self.frame)
        self.dateInspection.setMinimumSize(QtCore.QSize(0, 35))
        self.dateInspection.setMaximumSize(QtCore.QSize(16777215, 35))
        self.dateInspection.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateInspection.setDate(QtCore.QDate(2025, 1, 1))
        self.dateInspection.setObjectName("dateInspection")
        self.gridLayout.addWidget(self.dateInspection, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnEdit = QtWidgets.QPushButton(self.frame_3)
        self.btnEdit.setMinimumSize(QtCore.QSize(150, 35))
        self.btnEdit.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEdit.setStyleSheet("")
        self.btnEdit.setObjectName("btnEdit")
        self.verticalLayout_3.addWidget(self.btnEdit)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Input Dialog"))
        self.cmbxAcceptedOrRejected.setItemText(0, _translate("Dialog", "Acceptance"))
        self.cmbxAcceptedOrRejected.setItemText(1, _translate("Dialog", "Rejection"))
        self.cmbxWalkthroughOrButton.setItemText(0, _translate("Dialog", "Walkthrough"))
        self.cmbxWalkthroughOrButton.setItemText(1, _translate("Dialog", "Warranty"))
        self.projectid_label_2.setText(_translate("Dialog", "Accepted or Rejected:"))
        self.label_17.setText(_translate("Dialog", "Enter Inspection Date (mm-dd-yyyy)"))
        self.projectid_label.setText(_translate("Dialog", "Walkthrough or Warranty:"))
        self.dateInspection.setDisplayFormat(_translate("Dialog", "MM/dd/yyyy"))
        self.btnEdit.setText(_translate("Dialog", "Done"))
import resources_rc
